src/objects/Log__c.object
<CustomObject>
    <fields>
        <fullName>TransactionId__c</fullName>
        <externalId>true</externalId>
        <label>Transaction ID</label>
        <length>36</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Log</label>
    <nameField>
        <displayFormat>Log-{00000}</displayFormat>
        <label>Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/LogTriggerHandler.cls
public without sharing class LogTriggerHandler extends SObjectTriggerHandler {

    /*protected override void executeBeforeInsert(List<SObject> newRecordList) {
        List<Log__c> newLogList = (List<Log__c>)newRecordList;

        for(Log__c newLog : newLogList) {
            this.setTransactionId(newLog);
        }
    }

    protected override void executeBeforeUpdate(List<SObject> updatedRecordList, Map<Id, SObject> updatedRecordListMap, List<SObject> oldRecordList, Map<Id, SObject> oldRecordMap) {
        List<Log__c> updatedLogList = (List<Log__c>)updatedRecordList;
        Map<Id, Log__c> oldLogMap   = (Map<Id, Log__c>)oldRecordMap;

        for(Log__c updatedLog : updatedLogList) {
            Log__c oldLog = oldLogMap.get(updatedLog.Id);

            this.setTransactionId(updatedLog, oldLog);
        }
    }

    private void setTransactionId(Log__c updatedLog, Log__c oldLog) {
        // You probably don't want to allow the UUID to change, so add an error
        if(updatedLog.TransactionId__c != oldLog.TransactionId__c) updatedLog.TransactionId__c.addError('Transaction ID cannot be changed');

        // If it's a new field, you can have the UUID set the next time the record is updated
        if(!UUID.isValid(updatedLog.TransactionId__c)) this.setTransactionId(updatedLog);
    }

    private void setTransactionId(Log__c log) {
        if(UUID.isValid(log.TransactionId__c)) return;

        log.TransactionId__c = new UUID().getValue();
    }*/

}