src/objects/NebulaRecordTypesSettings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Controls the behavior of the class SObjectRecordTypes.cls</description>
    <fields>
        <fullName>LazyLoad__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Determines if a separate query is executed for each SObject (lazy load enabled), or if a single query is used to pre-load all record types (lazy load disabled)</description>
        <inlineHelpText>Determines if a separate query is executed for each SObject (lazy load enabled), or if a single query is used to pre-load all record types (lazy load disabled)</inlineHelpText>
        <label>Lazy Load</label>
        <type>Checkbox</type>
    </fields>
    <label>Nebula Record Types Settings</label>
</CustomObject>

src/classes/SObjectRecordTypes_Tests.cls
@isTest
private class SObjectRecordTypes_Tests {

    private class LeadRecordTypes extends SObjectRecordTypes {
        // Test subclass that extends SObjectRecordTypes
        public LeadRecordTypes() {
            super(Schema.SObjectType.Lead);
        }
    }

    @isTest
    static void allRecordTypesById() {
        List<RecordType> expectedRecordTypeList = [SELECT Id, DeveloperName FROM RecordType WHERE SObjectType = 'Lead'];

        Test.startTest();

        System.assertEquals(expectedRecordTypeList.size(), new SObjectRecordTypes_Tests.LeadRecordTypes().ALL_RECORD_TYPES_BY_ID.size());
        for(RecordType recordType : expectedRecordTypeList) {
            System.assert(new SObjectRecordTypes_Tests.LeadRecordTypes().ALL_RECORD_TYPES_BY_ID.containsKey(recordType.Id));
        }

        Test.stopTest();
    }

    @isTest
    static void allRecordTypesByDeveloperName() {
        List<RecordType> expectedRecordTypeList = [SELECT Id, DeveloperName FROM RecordType WHERE SObjectType = 'Lead'];

        Test.startTest();

        System.assertEquals(expectedRecordTypeList.size(), new SObjectRecordTypes_Tests.LeadRecordTypes().ALL_RECORD_TYPES_BY_DEVELOPER_NAME.size());
        for(RecordType recordType : expectedRecordTypeList) {
            System.assert(new SObjectRecordTypes_Tests.LeadRecordTypes().ALL_RECORD_TYPES_BY_DEVELOPER_NAME.containsKey(recordType.DeveloperName));
        }

        Test.stopTest();
    }

    @isTest
    static void queryIsCached_when_lazyLoadEnabled() {
        NebulaRecordTypesSettings__c recordTypesSettings = NebulaRecordTypesSettings__c.getInstance();
        recordTypesSettings.LazyLoad__c = true;
        upsert recordTypesSettings;

        Test.startTest();

        System.assertEquals(0, Limits.getQueries());
        for(Integer i = 0; i < 10; i++) {
            System.debug(new SObjectRecordTypes_Tests.LeadRecordTypes().ALL_RECORD_TYPES_BY_ID);
        }

        System.assertEquals(1, Limits.getQueries());

        Test.stopTest();
    }

    @isTest
    static void queryIsCached_when_lazyLoadDisabled() {
        NebulaRecordTypesSettings__c recordTypesSettings = NebulaRecordTypesSettings__c.getInstance();
        recordTypesSettings.LazyLoad__c = false;
        upsert recordTypesSettings;

        Test.startTest();

        System.assertEquals(0, Limits.getQueries());
        for(Integer i = 0; i < 10; i++) {
            System.debug(new SObjectRecordTypes_Tests.LeadRecordTypes().ALL_RECORD_TYPES_BY_ID);
        }

        System.assertEquals(1, Limits.getQueries());

        Test.stopTest();
    }

}