src/objects/TriggerHandlerSettings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Controls the behavior of the class SObjectTriggerHandler.cls</description>
    <fields>
        <fullName>ExecuteTriggers__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Controls if any trigger handler classes run its execute() method. This should always be enabled unless you are doing a data fix, etc and need to temporarily disable all triggers.</description>
        <inlineHelpText>Controls if any trigger handler classes run its execute() method. This should always be enabled unless you are doing a data fix, etc and need to temporarily disable all triggers.</inlineHelpText>
        <label>Execute Triggers</label>
        <type>Checkbox</type>
    </fields>
    <label>Trigger Handler Settings</label>
</CustomObject>

src/classes/SObjectTriggerHandler_Tests.cls
@isTest
private class SObjectTriggerHandler_Tests {

    private class LeadTriggerHandler extends SObjectTriggerHandler {
        public LeadTriggerHandler() {
            super(true);
        }
        public override void executeBeforeInsert(List<SObject> newRecordList) {
            List<Lead> newLeadList = (List<Lead>)newRecordList;

            for(Lead newLead : newLeadList) {
                this.setStatus(newLead);
            }
        }

        private void setStatus(Lead lead) {
            // Add logic here. Methods should be simple & independent from each other (except for overloaded methods)
            lead.Status = 'Open - Not Contacted';
        }
    }

    @testSetup
    static void setupData() {
        List<Lead> leadList = new List<Lead>();
        for(Integer i = 0; i < 5; i++) {
            Lead lead = new Lead(
                Company  = 'My Test Company',
                LastName = 'Gillespie'
            );
            leadList.add(lead);
        }
        insert leadList;
    }

    @isTest
    static void shouldNotExecuteTriggers() {
        TriggerHandlerSettings__c triggerHandlerSettings = TriggerHandlerSettings__c.getInstance();
        triggerHandlerSettings.ExecuteTriggers__c = false;
        upsert triggerHandlerSettings;

        List<Lead> leadList = [SELECT Id, Status FROM Lead];

        LeadTriggerHandler leadTriggerHandler = new LeadTriggerHandler();
        leadTriggerHandler.context    = SObjectTriggerHandler.TriggerContext.BEFORE_INSERT;
        leadTriggerHandler.recordList = leadList;

        Test.startTest();

        leadTriggerHandler.execute();

        Test.stopTest();
    }

    @isTest
    static void executeAllContexts() {
        List<Lead> leadList = [SELECT Id, Status FROM Lead];

        LeadTriggerHandler leadTriggerHandler = new LeadTriggerHandler();
        leadTriggerHandler.recordList = leadList;

        Test.startTest();

        for(SObjectTriggerHandler.TriggerContext context : SObjectTriggerHandler.TriggerContext.values()) {
            leadTriggerHandler.context = context;
            leadTriggerHandler.execute();
        }

        Test.stopTest();
    }

    @isTest
    static void executeBeforeInsert() {
        List<Lead> leadList = [SELECT Id, Status FROM Lead];

        LeadTriggerHandler leadTriggerHandler = new LeadTriggerHandler();
        // Set the variables for the relevant context
        leadTriggerHandler.context    = SObjectTriggerHandler.TriggerContext.BEFORE_INSERT;
        leadTriggerHandler.recordList = leadList;

        Test.startTest();

        leadTriggerHandler.execute();

        Test.stopTest();
    }

    @isTest
    static void executeBeforeUpdate() {
        List<Lead> leadList = [SELECT Id, Status FROM Lead];

        LeadTriggerHandler leadTriggerHandler = new LeadTriggerHandler();
        // Set the variables for the relevant context
        leadTriggerHandler.context       = SObjectTriggerHandler.TriggerContext.BEFORE_UPDATE;
        leadTriggerHandler.recordList    = leadList;
        leadTriggerHandler.recordMap     = new Map<Id, Lead>(leadList);
        leadTriggerHandler.oldRecordList = leadList;
        leadTriggerHandler.oldRecordMap  = new Map<Id, Lead>(leadList);

        Test.startTest();

        leadTriggerHandler.execute();

        Test.stopTest();
    }

}